name: AdvancedMiningSystem
main: Paradise\Mining\Main
version: 1.0.0
api: 5.0.0
depend: [EconomyAPI]
author: Paradise

permissions:
  advancedmining.admin:
    default: op
    description: Allows access to all AdvancedMining admin commands

# Adding virion dependency for FormsUI
virions:
  - FormsUI