# AdvancedMiningSystem Configuration

# World where the mining system is enabled
mining-world: "factions"

# Basic rewards
stone-reward: 2

# Special blocks rewards
special-blocks:
  gold_ore: 10
  diamond_ore: 50
  ancient_debris: 100
  epic_ore: 500

# Special blocks regeneration
regeneration:
  enabled: true
  min-time: 300 # 5 minutes
  max-time: 600 # 10 minutes

# Mining zones
mining-zones:
  zone1:
    pos1: [100, 64, 100]
    pos2: [200, 100, 200]
    pvp: true

# Mining events
events:
  enabled: true
  interval: 3600 # 1 hour
  duration: 300 # 5 minutes
  announcement-radius: 100

# Mining upgrades
upgrades:
  level1:
    multiplier: 2
    price: 10000
  level2:
    multiplier: 3
    price: 25000
  level3:
    multiplier: 4
    price: 50000

# NPC traders
traders:
  enabled: true
  locations:
    trader1: [0, 64, 0]
    trader2: [100, 64, 100]